---
proship:
  ship-request:
    uri: http://psprck-vdwn002.wsgcdev.local:3278/pws-rest/ils
  services: U11,U1R,UGO

shiprequest:
  fields:
    to:
      randomize: CCN_CARTON_NUMBER,CCN_PICKTKT_CTRL,CCN_ORDER_NUMBER,WEIGHT,SERVICE,DIMENSION

server:
  port: 8086

